# Generated by Django 3.0.7 on 2020-12-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20201223_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='issueRaised',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
