# Generated by Django 3.0.7 on 2020-12-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
